{
 "title": "NGINX Service Dashboard",
 "description": "Monitoring for NGINX Ingress Based Services",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App Name",
    "query": {
     "query": "label_values(nginx_ingress_controller_connect_duration_seconds_bucket,host)"
    }
   },
   {
    "name": "quantile",
    "label": "Quantile",
    "query": "0.99, 0.95, 0.9, 0.75, 0.5, 0.25"
   }
  ]
 },
 "panels": [
  {
   "title": "Time to Certificate Expiry",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_ingress_controller_ssl_expire_time_seconds{host=\"$app\"} - time()",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration $quantile-th Percentile over 5m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{host=\"$app\"}[5m])))",
     "legendFormat": "Request Duration"
    }
   ]
  },
  {
   "title": "Response Duration $quantile-th Percentile over 5m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum by(le) (rate(nginx_ingress_controller_response_duration_seconds_bucket{host=\"$app\"}[5m])))",
     "legendFormat": "Response Time"
    }
   ]
  },
  {
   "title": "Time to Upstream Connect $quantile Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum by(le) (rate(nginx_ingress_controller_connect_duration_seconds_bucket{host=\"$app\"}[5m])))",
     "legendFormat": "Time to Connect"
    }
   ]
  },
  {
   "title": "Time to First Header $quantile Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum by(le) (rate(nginx_ingress_controller_header_duration_seconds_bucket{host=\"$app\"}[5m])))",
     "legendFormat": "Time to Header"
    }
   ]
  },
  {
   "title": "Requests Rate per Minute by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by(method) (rate(nginx_ingress_controller_requests{host=\"$app\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Rate per Minute by Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by(status) (rate(nginx_ingress_controller_requests{host=\"$app\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NGINX Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "rate(nginx_ingress_controller_nginx_process_requests_total[1m])",
     "legendFormat": "Requests"
    }
   ]
  }
 ]
}